//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopElectronics.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long ID { get; set; }
        public string ProductName { get; set; }
        public string Alias { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public int Quantity { get; set; }
        [DisplayName("Upload Image")]
        public string Image { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string MetaKeyword { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> HomeFlag { get; set; }
        public Nullable<bool> HotFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Supplierss Supplierss { get; set; }
    }
}
